export const SET_PRODUCTS = "SET_PRODUCTS";
export const TOGGLE_PRODUCT_CHECKED = "TOGGLE_PRODUCT_CHECKED";
export const REMOVE_CHECKED_PRODUCTS = "REMOVE_CHECKED_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
